# Generated by Django 2.1.1 on 2020-06-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(choices=[('아이디검증', '아이디검증'), ('쇼핑솔루션', '쇼핑솔루션'), ('SNS솔루션', 'SNS솔루션'), ('기타', '기타')], default='아이디검증', max_length=10, verbose_name='솔루션')),
                ('category', models.CharField(choices=[('일반문의', '일반문의'), ('제안요청', '제안요청'), ('버그신고', '버그신고'), ('탈퇴신청', '탈퇴신청'), ('기타', '기타')], default='일반문의', max_length=10, verbose_name='카테고리')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='작성자명')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='회사명')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='직책')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='연락처')),
                ('email', models.CharField(default='', max_length=250, verbose_name='이메일')),
                ('comment', models.TextField(blank=True, default='', verbose_name='문의내용')),
                ('file0', models.FileField(blank=True, upload_to='inquiry_file/%Y/%m/%d/', verbose_name='첨부파일')),
                ('answer', models.TextField(blank=True, default='', verbose_name='문의답변')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '온라인문의',
                'verbose_name_plural': '온라인문의',
            },
        ),
    ]
