# Generated by Django 2.1.1 on 2020-06-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'inquiry', 'verbose_name_plural': 'inquiry'},
        ),
    ]
