# Generated by Django 2.1.1 on 2020-06-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('allowed_ip', models.CharField(blank=True, max_length=32, verbose_name='허용 아이피')),
                ('expired_at', models.DateTimeField(auto_now_add=True,blank=True, null=True, verbose_name='만료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, verbose_name='구매일')),
                ('updated_at', models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='갱신일')),
                ('idfunnel_at', models.DateTimeField(null=True, verbose_name='아이디파인더만기일')),
                ('shopfinder_at', models.DateTimeField(null=True, verbose_name='쇼핑몰파인더만기일')),
                ('snsfinder_at',  models.DateTimeField(null=True, verbose_name='SNS파인더만기일')),
                ('debug_level',  models.IntegerField(default=20, verbose_name='디버그 레벨')),
            ],
        ),
    ]
