# Generated by Django 3.2.9 on 2022-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='debug_level',
            field=models.CharField(blank=True, default='20', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='만기일'),
        ),
        migrations.AddField(
            model_name='member',
            name='login_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='로그인IPMAC'),
        ),
    ]
