# Generated by Django 3.2.9 on 2021-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('keyword', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
