# Generated by Django 2.1.1 on 2020-06-18 13:56

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('공지사항', '공지사항')], default='News', max_length=10, verbose_name='카테고리')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='제목')),
                ('memo', models.CharField(blank=True, default='', max_length=100, verbose_name='설명')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('image0', imagekit.models.fields.ProcessedImageField(blank=True, default='', null=True, upload_to='data/%Y/%m/%d/', verbose_name='커버 이미지')),
                ('file0', models.FileField(blank=True, null=True, upload_to='data/%Y/%m/%d/', verbose_name='파일')),
                ('view', models.IntegerField(blank=True, default=0, verbose_name='조회수')),
                ('author', models.CharField(blank=True, default='', max_length=20, verbose_name='작성자')),
                ('display', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('permanent', models.BooleanField(default=False, verbose_name='공지 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('마케팅자료', '마케팅자료')], default='News', max_length=10, verbose_name='카테고리')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='제목')),
                ('memo', models.CharField(blank=True, default='', max_length=100, verbose_name='설명')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('image0', imagekit.models.fields.ProcessedImageField(blank=True, default='', null=True, upload_to='data/', verbose_name='커버 이미지')),
                ('file0', models.FileField(blank=True, null=True, upload_to='data/', verbose_name='파일')),
                ('view', models.IntegerField(blank=True, default=0, verbose_name='조회수')),
                ('author', models.CharField(blank=True, default='', max_length=20, verbose_name='작성자')),
                ('display', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('permanent', models.BooleanField(default=False, verbose_name='공지 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '마케팅자료',
                'verbose_name_plural': '마케팅자료',
            },
        ),        
    ]
