# Generated by Django 3.2.9 on 2021-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('공지사항', '마케팅자료')], default='News', max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='library',
            name='category',
            field=models.CharField(choices=[('공지사항', '마케팅자료')], default='News', max_length=10, verbose_name='카테고리'),
        ),
    ]
